<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'supplier_type'   => 'infrastructure',
                'commercial_name' => 'Interserver',
                'legal_name'      => 'InterServer, Inc.',
                'tax_id'          => 'US123456789',
                'contact_person'  => 'John Doe',
                'contact_email'   => 'billing@interserver.net',
                'contact_phone'   => '+1-201-605-1440',
                'website'         => 'https://www.interserver.net',
                'address'         => '1100 Empire Blvd, Secaucus, NJ 07094, USA',
                'bank_details'    => 'Wire Transfer / PayPal: billing@interserver.net',
                'notes'           => 'Proveedor de VPS y servidores dedicados en la nube.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'infrastructure',
                'commercial_name' => 'Neubox',
                'legal_name'      => 'Neubox Internet S.A. de C.V.',
                'tax_id'          => 'NEU040506ABC',
                'contact_person'  => 'Soporte Neubox',
                'contact_email'   => 'contacto@neubox.net',
                'contact_phone'   => '33-800-638-2691',
                'website'         => 'https://neubox.com',
                'address'         => 'Av. Aviación 5051, Zapopan, Jalisco, México',
                'bank_details'    => 'BBVA Bancomer - Cuenta: 0123456789 - Clabe: 012345678901234567',
                'notes'           => 'Registro de dominios y hosting compartido.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'services',
                'commercial_name' => 'Telmex',
                'legal_name'      => 'Teléfonos de México S.A.B. de C.V.',
                'tax_id'          => 'TEM840315KT6',
                'contact_person'  => 'Atención Corporativa',
                'contact_email'   => 'corporativo@telmex.com',
                'contact_phone'   => '800-123-3232',
                'website'         => 'https://telmex.com',
                'address'         => 'Parque Vía 198, Col. Cuauhtémoc, CDMX, México',
                'bank_details'    => 'Domiciliación a tarjeta corporativa',
                'notes'           => 'Proveedor de internet simétrico y líneas de telefonía fija.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'services',
                'commercial_name' => 'Totalplay',
                'legal_name'      => 'Total Play Telecomunicaciones S.A. de C.V.',
                'tax_id'          => 'TPT1009187D3',
                'contact_person'  => 'Soporte Totalplay Empresarial',
                'contact_email'   => 'empresarial@totalplay.com.mx',
                'contact_phone'   => '800-303-0303',
                'website'         => 'https://www.totalplay.com.mx',
                'address'         => 'Av. San Jerónimo 252, Col. La Otra Banda, CDMX, México',
                'bank_details'    => 'Pago referenciado en ventanilla o transferencia',
                'notes'           => 'Enlace de respaldo de fibra óptica.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'services',
                'commercial_name' => 'Servicio de Basura Municipal',
                'legal_name'      => 'Ayuntamiento Municipal - Servicios Públicos',
                'tax_id'          => 'MUN850101XYZ',
                'contact_person'  => 'Oficina de Recaudación',
                'contact_email'   => 'basura@ayuntamiento.gob.mx',
                'contact_phone'   => '55-1234-5678',
                'website'         => 'https://ayuntamiento.gob.mx',
                'address'         => 'Plaza Principal S/N, Centro',
                'bank_details'    => 'Pago de derechos anual en ventanilla municipal',
                'notes'           => 'Servicio de recolección de basura comercial y residuos no peligrosos.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'services',
                'commercial_name' => 'Limpieza Semanal - EcoClean',
                'legal_name'      => 'EcoClean Servicios de Limpieza Integral S.A. de C.V.',
                'tax_id'          => 'ESL150824AA1',
                'contact_person'  => 'Patricia Gómez',
                'contact_email'   => 'contacto@ecoclean.com.mx',
                'contact_phone'   => '55-9876-5432',
                'website'         => 'https://ecoclean.com.mx',
                'address'         => 'Calle Limón 123, Col. Lindavista, CDMX, México',
                'bank_details'    => 'Santander - Cuenta: 9876543210 - Clabe: 014180987654321022',
                'notes'           => 'Servicio contratado los martes y jueves de cada semana.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'administrative',
                'commercial_name' => 'Papelería Lozano',
                'legal_name'      => 'Distribuidora de Papelería y Oficina Lozano S.A.',
                'tax_id'          => 'DPO991231888',
                'contact_person'  => 'Carlos Lozano',
                'contact_email'   => 'ventas@papelerialozano.com',
                'contact_phone'   => '55-5555-4444',
                'website'         => 'https://papelerialozano.com',
                'address'         => 'Av. Reforma 456, Col. Juárez, CDMX, México',
                'bank_details'    => 'Banorte - Cuenta: 555666777 - Clabe: 072180005556667771',
                'notes'           => 'Suministros de oficina, papel, tóner y artículos administrativos.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'supplier_type'   => 'hardware',
                'commercial_name' => 'Dell México',
                'legal_name'      => 'Dell México S.A. de C.V.',
                'tax_id'          => 'DME921102A76',
                'contact_person'  => 'Ejecutivo de Cuenta Dell',
                'contact_email'   => 'ventas_corporativas@dell.com',
                'contact_phone'   => '800-505-3355',
                'website'         => 'https://www.dell.com/es-mx',
                'address'         => 'Paseo de la Reforma 2620, Col. Lomas Altas, CDMX, México',
                'bank_details'    => 'CitiBanamex - Cuenta: 4444 - Clabe: 002180000000004444',
                'notes'           => 'Proveedor de servidores físicos, computadoras y equipamiento de red.',
                'status'          => 1,
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('fin_suppliers')->insertBatch($data);
    }
}
